service: authentication-passport
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: 'us-east-1'
  environment:
    LOCALSTACK_HOSTNAME: ${env:LOCALSTACK_HOSTNAME, "localhost"}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
           - dynamodb:Query
           - dynamodb:GetItem
           - dynamodb:UpdateItem
           - dynamodb:PutItem
           - dynamodb:Scan
          Resource: "*"

resources:
  Resources:
    AssetTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: customers
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

functions:
  - ${file(functions.yml)}

plugins:
  - serverless-offline

